#:schema node_modules/wrangler/config-schema.json
name = "lifan-dev"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

routes = [
  { pattern = "lifan.dev", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

# [[d1_databases]]
# binding = "DB"
# database_name = "lifan-dev-db"
# database_id = "to-be-set"
